server:
  port: 8080
spring:
  data:
    mongodb:
      authentication-database: admin
      database: test
      uri: mongodb+srv://dustdrivedev:2HMxc9JN0cqPd2nb@cluster0.ovtfl8q.mongodb.net/dustdrive_dev

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration